### ISSUE TITLE
Cannot customize DEFAULT_FONT_STACK

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1026]
I think we introduced a bug into element.ts:
https://github.com/0xfe/vexflow/blob/2c77ad2af0a5cc79ba5857d3c640b6dd1280741d/src/element.ts#L65-L66

I think the original code allowed developers to customize `Vex.Flow.DEFAULT_FONT_STACK`, which would affect the music notation font. DEFAULT_FONT_STACK is no longer referenced anywhere in the core library.

I noticed this while cleaning up `vexflow_test_helpers.js`, which sets VF.DEFAULT_FONT_STACK to generate the different outputs. Now all the tests are rendered in Bravura.

**Comment by ronyeh** [comment]
OK, I think I fixed it by changing the above two lines to:

```
    this.fontStack = Vex.Flow.DEFAULT_FONT_STACK;
    this.musicFont = Vex.Flow.DEFAULT_FONT_STACK[0];
```

However, I noticed that Petaluma note heads are slightly detached from the stems. Did we change some glyph or stem offsets recently?

<img width="1491" alt="Detached" src="https://user-images.githubusercontent.com/239113/121259808-65cb3380-c865-11eb-9b32-ec200d1ce02c.png">

**Comment by 0xfe** [comment]
Yikes, thanks for catching this Ron. Adding @rvilarl to dig in here.

This should definitely have caused the visual regression tests to fail. Not clear why it didn't?

**Comment by 0xfe** [comment]
Also, I should have caught this, but many of the `Vex.Flow.XXX` constants are part of the vexflow interface, so we should revert those -- lots of external systems rely on it.

**Comment by ronyeh** [comment]
By default we only render and diff PNGs for Bravura. Maybe it's time to
render PNGs for all three fonts, even though it slows down the visual diff
tests?

**Comment by ronyeh** [comment]
If we do visual diffing for all 3 fonts, it might have caught the
regression of Petaluma stems getting detached from the note heads. I'd vote
for turning on all three fonts from now on. In my previous tests it didn't
slow it down by that much. Plus I'm running a 2016 MacBook pro. I hear the
new ones are even faster 😁.

**Comment by rvilarl** [comment]
> By default we only render and diff PNGs for Bravura. Maybe it's time to render PNGs for all three fonts, even though it slows down the visual diff tests?

This explains why the visual diff did not catch the bug. +1 to turn on all the three fonts.

**Comment by AaronDavidNewman** [comment]
>> I noticed that Petaluma note heads are slightly detached from the stems

This must have happened pretty recently.  I merged with master on 5/30 and I don't see this on my branch.

**Comment by rvilarl** [comment]
> OK, I think I fixed it by changing the above two lines to:
> ```
> this.fontStack = Vex.Flow.DEFAULT_FONT_STACK;
> this.musicFont = Vex.Flow.DEFAULT_FONT_STACK[0];
> ```

@ronyeh  I checked out 6b7fe6b2652 where the lines above were still not changed and `flow.html` is also not showing petaluma fonts. Did you make the fix above on master? I tried that as well and it did not work.

**Comment by ronyeh** [comment]
I haven't sent in a PR for that fix yet. If you guys want, I can send in
one so Mohit can merge into master.

**Comment by ronyeh** [comment]
See: https://github.com/0xfe/vexflow/pull/1028

I no longer see the detached Petaluma note heads.... I'll have to see if I can repro it on my other branch!

In any case, I removed the constant `DefaultFontStack` and use `Flow.DEFAULT_FONT_STACK` everywhere. This allows a developer to customize the music font.

**Comment by 0xfe** [comment]
Thanks folks. I guess that explains why the visual regressions didn't catch the bug. Reviewing.
