### ISSUE TITLE
Migration from 3.0.9 to 4.0

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1200]
This meta issue tracks any known stumbling blocks when migrating a project from 3.0.9 to 4.0.

These stumbling blocks can be addressed in our CHANGELOG file.

One idea is to use `npm link` to point the VexTab project at VexFlow 4.0, and then see what errors pop up. You can do the same with your own project, and list some of the errors here.

We can promote some to independent issues, if they are bad enough to warrant a bug fix.

**Comment by 0xfe** [comment]
Ron, can you try it with https://github.com/0xfe/vextab please? I have instructions there around using `npm link`(see README) for developing with both VexFlow and VexTab at the same time.

Re: fields of `package.json` -- I'm no expert either, I really just used what worked without searching for the best way. I think if you have good representative TS packages to model off of, that would be great. Just be mindful of emerging complexity in the build pipeline -- it makes debugging really hard.  In general, I prefer simple imperfect workflows to ideal workflows.

**Comment by AaronDavidNewman** [comment]
I think there is an issue with our current build that we may want to fix before we release.  It looks like the symbol `Vex` in flow.ts:

![image](https://user-images.githubusercontent.com/5438280/139557347-00224dcb-2374-4fad-99d5-ace7e9a06ed4.png)

is only created in releases/vexflow-tests.js, which I assume was the output of the build at an earlier time.  If you don't have anything in your releases directory, the build will fail with unknown symbol 'Vex'.

I think it will work just to replace that line with:

``` typescript
const VF = Flow;
```

**Comment by ronyeh** [comment]
> I think there is an issue with our current build that we may want to fix before we release. It looks like the symbol `Vex` in vf_prefix_tests.ts:

This issue is fixed in my branch. With `declare let Vex: any;`:

https://github.com/ronyeh/vexflow/blob/e1b596ec17b76def76bdbb19835179fc6acd3d26/tests/vf_prefix_tests.ts#L93-L97

That test case is intentionally accessing `Vex.Flow` so we can compare it against direct access to the classes in TypeScript. I added those test cases a while back, and perhaps a bad merge/rebase killed a line.

We are just verifying that the global Vex.Flow exists, and things like Vex.Flow.Accidental are equivalent to Accidental.

**Comment by rvilarl** [comment]
Starting the migration with PianoPlay, first issue imports

![image](https://user-images.githubusercontent.com/22865285/139559015-6cce1dd2-438c-4505-9f77-94b78e8cc319.png)

**Comment by rvilarl** [comment]
Migration done!
TS migrated version
https://michaelecke.com/pianoplayts/#/home
Original (1.2.93)
https://michaelecke.com/pianoplay/#/home

You can open any MusicXML file

They look quite different indeed

![Captura de pantalla de 2021-10-31 00-33-06](https://user-images.githubusercontent.com/22865285/139560304-7fdf7106-5461-4846-a14b-ac037dcc9cf1.png)

![Captura de pantalla de 2021-10-31 00-32-59](https://user-images.githubusercontent.com/22865285/139560311-32c9adac-643b-479d-bdfd-4dc14f576d48.png)

**Comment by rvilarl** [comment]
The notes are going beyond the staves :( @sschmidTU you know that I use VexFlow with OSMD, any tip?

**Comment by AaronDavidNewman** [comment]
This looks like an issue with clefNote.   What are you using to compute the width - is it `preCalculateMinTotalWidth`?

**Comment by rvilarl** [comment]
OSMD uses the following:
```
      minStaffEntriesWidth = formatter.preCalculateMinTotalWidth(allVoices) / unitInPixels
      * this.rules.VoiceSpacingMultiplierVexflow
      + this.rules.VoiceSpacingAddendVexflow
      + maxStaffEntries * staffEntryFactor; // TODO use maxStaffEntriesPlusAccidentals here as well, adjust spacing
```
@sschmidTU this is the calculation, is not it? By the way I will try the TODO

**Comment by rvilarl** [comment]
@AaronDavidNewman @sschmidTU I made an error updating the web page and I left and early version of the TS migrated code. The latest one look much better indeed!

![Captura de pantalla de 2021-10-31 06-37-57](https://user-images.githubusercontent.com/22865285/139569656-bc505a2d-fb8e-4fb0-b1ff-871af08bce20.png)

**Comment by rvilarl** [comment]
It looks also finally better than 1.2.93! This is great! I will try wit other scores.

**Comment by rvilarl** [comment]
@ronyeh I also tried with your branch in #1163 commit 50129fca5db4ca488d9bbd36fba7663f62651454 and I get the following errors (not many):

![Captura de pantalla de 2021-10-31 09-18-06](https://user-images.githubusercontent.com/22865285/139574322-3f6aabba-1ae2-466f-8db5-1fae61a1bf70.png)

**Comment by ronyeh** [comment]
Oh thanks for your help! My current commit that I've tested is b1473d90cc618a073af336bc4125e8510027222b  on https://github.com/ronyeh/vexflow/tree/setFont

The @loadFonts bit was inspired by your tsconfig paths for @bravura, @gonville, @petaluma. That seems like the biggest issue to figure out. Is it a tsconfig problem?

I assume your project is 100% TS and you are compiling with vexflow (via npm install / npm link)?

**Comment by rvilarl** [comment]
yes, 100% TS via npm install / npm link

**Comment by rvilarl** [comment]
Same output with b1473d90cc618a073af336bc4125e8510027222b

![Captura de pantalla de 2021-10-31 09-28-48](https://user-images.githubusercontent.com/22865285/139574545-9d698b06-7d4b-46a9-9c02-4549397dc391.png)

**Comment by ronyeh** [comment]
The FontFace API is part of the web standard, and on my vscode is available via TypeScript's lib.dom.d.ts.
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts

I didn't have to do anything for VSCode to recognize this type. For example `interface HTMLElement extends Element` is also defined in lib.dom.d.ts.

I wonder why your VSCode doesn't recognize that type?

**Comment by rvilarl** [comment]
I might be missing a npm install in my project? I say that because I have no problem compiling b1473d90cc618a073af336bc4125e8510027222b.

**Comment by ronyeh** [comment]
I found a related question and answer on:
* https://stackoverflow.com/questions/69052698/cannot-find-name-fontface-ts2304
* https://github.com/Microsoft/TypeScript/issues/30984#issuecomment-831643164

Does that mean I can just add that typings file as a dependency for VexFlow?

**Comment by rvilarl** [comment]
I installed `npm install --save @types/css-font-loading-module` and I still get the problem :(

> Does that mean I can just add that typings file as a dependency for VexFlow?

I do not know

**Comment by ronyeh** [comment]
Weird. But when you compile my branch, it compiles fine? If you ctrl+click (or alt+click on Mac) the name `FontFace`, does it bring you to lib.dom.d.ts?

Anyways, thanks for your help. I'll see if I can repro this.

**Comment by ronyeh** [comment]
Can you dig around and see if you can find your copy of lib.dom.d.ts? Where is it stored? Which distro / OS are you using?

Even though the TS compiler and VS Code should recognize FontFace natively, I don't want this to be a stumbling block for developers who want to use VexFlow.

Either we need to find a npm package (of typings) that will make this work seamlessly, or perhaps I can declare FontFace as a global any, and then just drop in an eslint-disable to squash the warnings, haha.

**Comment by rvilarl** [comment]
I will do.

I have also placed complete paths in imports on all the files in 
migration/4.0. This is also to avoid the problems with linux...

I use Fedora  34

**Comment by ronyeh** [comment]
I pushed one last update for tonight.

cbebfb03ae45baa2d036e7248a7d4adb01abad10

I just added a src/types/fontface.d.ts

Hopefully that will allow the types to work!

**Comment by ronyeh** [comment]
This is what the file looks like:
https://github.com/ronyeh/vexflow/commit/cbebfb03ae45baa2d036e7248a7d4adb01abad10

https://github.com/ronyeh/vexflow/tree/setFont

Good night! Putting my laptop (and me) to sleep. :-)

**Comment by rvilarl** [comment]
Good night! Here the ouput, still an error but different.

![Captura de pantalla de 2021-10-31 11-28-15](https://user-images.githubusercontent.com/22865285/139578305-30180335-4bc6-4823-ac25-c5416a8da511.png)

**Comment by ronyeh** [comment]
Just updating folks on this thread. Rodrigo and I are collaborating over chat at the moment. We have figured out the FontFace error. The API declaration was introduced in TypeScript 4.4, and he's running TS 4.3.5. So I put in @ts-ignore comments in the appropriate places to ask VS Code / TS compiler to ignore errors in that method for now.

I'm now trying to figure out our path alias issue.

**Comment by ronyeh** [comment]
See this thread for first steps on migrating your project to 4.0.0:
https://github.com/0xfe/vexflow/pull/1214

Quick Start:
```
cd /path/to/your/project
npm uninstall vexflow
npm install https://vexflow-demo.surge.sh/4.0.0-alpha-1.tgz
```

Please respond with the errors you're seeing. I can help point you in the right direction.

Or if I'm away from keyboard, I'm sure Rodrigo can also help, since he seems to be intimately familiar with my code.... Also, we're 8 hrs offset from each other, so you'll almost have 24 hr tech support for this upgrade. One time special offer! ;-)

**Comment by rvilarl** [comment]
@sschmidTU Ron and I decided to give a try at vanilla OSMD migration without my app PianoPlay.
These are the steps:
```
mkdir integration
cd integration
git clone https://github.com/ronyeh/vexflow
cd vexflow
git checkout 4.0.0-alpha
npm install 
npm run reference
cd ..
git clone https://github.com/opensheetmusicdisplay/opensheetmusicdisplay
cd opensheetmusicdisplay/
npm install
npm uninstall vexflow
sudo npm link ../vexflow/
npm run build
```
@roney this works! No problem

**Comment by rvilarl** [comment]
@sschmidTU can you try the mini guide above and provide some feedback/help? Am I missing something or doing something wrong? I am not progressing. :(

**Comment by ronyeh** [comment]
I successfully migrated VexTab to VexFlow 4.0.0.

This is the patch for the migration of VexTab: https://github.com/0xfe/vextab/pull/137

I had to modify VexFlow a bit to restore some backwards compatibility. I also added some new accessors:
https://github.com/ronyeh/vexflow/commit/e5747baaa573d39a357b9767a61aa74f89781da2

I can cherry pick that commit and submit it as a separate PR if it makes it easier to merge.

Here is the process I used to migrate VexTab. It might help others with migrating their own projects to VexFlow 4.

```
git clone git@github.com:0xfe/vextab.git .

npm install

npm run start

    Everything works, because it is using VexFlow 3.0.8. View the tests at http://localhost:9005/

~~~TIME TO MIGRATE!~~~

delete node_modules/vexflow/

npm run start

    ERROR: vextab/src/div.js
    Unable to resolve path to module 'vexflow'  import/no-unresolved
    This is expected, because I just deleted vexflow :-)

npm install vexflow-4.0.0-alpha-2.tgz

    Alternatively, clone vexflow from https://github.com/ronyeh/vexflow
    Check out the 4.0.0-alpha branch
    Build VexFlow 4 by running `grunt`
    Run `npm link` to register that branch. 
    Change back to the vextab/ directory.
    npm link vexflow

npm run watch

```

There were some errors, but I was able to debug & fix them. Not too bad.

Here are the screenshots after the VexTab migration.

![Playground](https://user-images.githubusercontent.com/239113/140599091-9717a49d-bc29-4fd0-a991-d985bb2f2d44.png)

![Tests](https://user-images.githubusercontent.com/239113/140599095-c95c67dd-637a-4c98-826e-ac50d7e69ec9.png)

**Comment by rvilarl** [comment]
> @sschmidTU can you try the mini guide above and provide some feedback/help? Am I missing something or doing something wrong? I am not progressing. :(

@ronyeh the problem in the migration is that the imported vex (ie.: Vex.Flow.StaveNote) can be used to instantiate an object:
`vfnote = new Vex.Flow.StaveNote(vfnoteStruct);`
but not as:
1) type `vfnote: Vex.Flow.StaveNote  = ...`
2) return type in functions `getNote():  Vex.Flow.StaveNote {...`

**Comment by rvilarl** [comment]
Several scores using the migration above in PianoPlay.
@ronyeh this is using #1214 without modification, this is very good! We must find a way though to avoid the usage of any in the migration of OSMD
![Captura de pantalla de 2021-11-06 14-52-49](https://user-images.githubusercontent.com/22865285/140612153-349a9074-f556-484c-9907-47ae49b85922.png)
![Captura de pantalla de 2021-11-06 14-59-20](https://user-images.githubusercontent.com/22865285/140612290-0a411c56-d501-45cd-83b2-46cd4b3943a6.png)
![Captura de pantalla de 2021-11-06 15-02-37](https://user-images.githubusercontent.com/22865285/140612404-b352a927-e789-43f1-9be6-52651d286ff4.png)
