### ISSUE TITLE
Dot distance from eighth note is miscalculated?

### ISSUE THREAD

**Issue by nitzanrh** [0xfe/vexflow#1588]
Hi there,

Based on ronyeh's jsfiddle from the Vexflow tutorial:
https://jsfiddle.net/ronyeh/4rt75dja/

The distance between the dot and the 8th note is much larger than the distance between the dot and the half note (or the quarter note at the end of the stave). This becomes more of an issue when there are two consecutive dotted eighth notes.

It seems to me like the dot's distance is relative to the note's flag rather than the note's circle, but perhaps I'm mistaken.

Cheers,
Nitzan Ravhon

**Comment by rvilarl** [comment]
I think that you are right. It is referenced to the flag. 4.2.2 separates the notes more, perhaps too match

https://jsfiddle.net/pb1mju0y/

**Comment by AaronDavidNewman** [comment]
Possibly this happened when we did some bug fixes for 2 noteheads.  Oddly enough, none of our 'dot_tests' have a single note head with beam up, that would have exposed this bug.

It must have worked in 3.0.9, based on the screenshots in the tutorial.

**Comment by AaronDavidNewman** [comment]
I was taking for granted that this is a bug, but I'm not so sure now.  According to Behind Bars, the dot can be placed after the flag if the flag would obscure the dot.  And here it is a little hazy, because that depends on 1) whether the note is a line or a space, or 2) the value of the flag, and 3) the engraving font and the length of the flag. 

For instance, here's a line note and a space note, dotted, with a 16th flag, Bravura font.

![image](https://github.com/0xfe/vexflow/assets/5438280/91889d97-a3c6-46b5-bf16-e580e81d6605)

I think if that were any close to the note it would hit the flag.  Where the space note, it looks a bit goofy off to the left.

So probably there is no new bug here, but we could conditionally improve the formatting for space notes and short flags in some cases.

Another option according to Gould is to lengthen the stem so that it would never obscure the dot (which seems like it would have its own issues).

**Comment by nitzanrh** [comment]
@rvilarl I don't believe this can be marked as complete.

Look at this example, still based on @ronyeh tutorial (with some tiny changes to the note's modifiers): 
https://jsfiddle.net/mnyv2dxj/1/

See how the dot on the E# is almost touching the Eb?

If think that if a decision has been made that the position of the dot is 'accurate', then at least it needs a larger margin/padding/distance from the following note.

**Comment by AaronDavidNewman** [comment]
@nitzanrh the issue was fixed in a later version (4.2.2) than the tutorial uses.  I updated the link in the fiddle here.  https://jsfiddle.net/AaronDavidNewman/f3e1m4n7/1/

If you feel inspired to update the examples in the wiki, go with it :)

**Comment by nitzanrh** [comment]
Hi @AaronDavidNewman ,

Thanks for pointing this out. 

It appears that the reason I'm still encountering this issue with my code is that I use preCalculateMinTotalWidth to get the stave's width, and usually the value is too small so the notes get somewhat cramped in - resulting in the dot getting really close to the next note.

Anyways this appears to be solved, now I need to fix my own code :)

Cheers guys, and thanks for the great work!

**Comment by rvilarl** [comment]
@nitzanrh take into account that preCalculateMinTotalWidth does not leave space for the clef / keys. You have to getNoteStartX. Have a look at system.ts

**Comment by nitzanrh** [comment]
> @nitzanrh take into account that preCalculateMinTotalWidth does not leave space for the clef / keys. You have to getNoteStartX. Have a look at system.ts

Yeah I take that into account, but still is some cases I get values that are somewhat too small. For example, a bar of 16 16th notes will look perfect, and does a bar of 4 quarter notes, however when I mix them up it come up not as consistent. But again, this might be due some other parts of my code (for example, i manually calculate my systems according to my stave's width, and sometime I need to add extra space for all the systems to be at the same width)

**Comment by AaronDavidNewman** [comment]
I think there were some fixes to preCalculateMinTotalWidth during 4.x development also.  So if you can find an example that can be extracted into a fiddle, I'll take a look at it.  It's supposed to allow extra space for cases like you mentioned, but there could be a bug.

**Comment by AaronDavidNewman** [comment]
I agree about the dot placement when the note head is on a space and the flag goes up.  If the note head is on a line, the flag drapes down further and the dot needs to be further out.  That case seems OK.  If the stem points down it also looks good.

So I think the ideal fix would be to drop a couple pixels of padding when the notehead is on a space and there is a flag, and the flag goes up.  There are probably corner cases when the noteheads are displaced or there are multiple notes in a chord that will make it tricksy.

These very small measures like the one with 4 quarter notes, it is true that the spacing in front or in back seems large, because the 1/4 notes are so close together.   Is that measure size based on 'preCalculateMinTotalWidth'?

**Comment by nitzanrh** [comment]
Yes I agree, when the stem points down the distance between the dot and the note is fine.

And yes, all the staves are based on 'preCalculateMinTotalWidth' with added Stave.defaultPadding (which I believe is 22).

Just for fun, you could try the JSFIddle with 'preCalculateMinTotalWidth' * 2 and see what happens; some measures actually look better (like the 4 quarter notes) but others look strange in terms of alignment

**Comment by nitzanrh** [comment]
Hey all, any news on this issue - specifically the dot's placement when the flag goes up?

Also, I tried to manually modify the dot position by calling Dot.SetXShift(), however this doesn't seem to have any effect. Dot.SetYShift() does work.

**Comment by rvilarl** [comment]
Hi, I have slightly modified the jsfiddle to avoid the double formating

https://jsfiddle.net/ph6wg5dv/1/

Do you find it better?

**Comment by rvilarl** [comment]
@AaronDavidNewman I think that with vexflow5 it looks better because the flag is located lower and, as you mentioned, it would obscure the0 dot.

**Comment by nitzanrh** [comment]
> Hi, I have slightly modified the jsfiddle to avoid the double formating
> 
> https://jsfiddle.net/ybpc7nhw/
> 
> Do you find it better?
> 
> And this is how it looks with vexflow5 alpha
> 
> https://jsfiddle.net/ph6wg5dv/2/

Yes this does look better in terms of formatting (although the dot placement is still a bit off).
If i understand correctly, the change you've made is calling format on the voice with the stave's width, rather than calling later formatToStave, correct? If so, why would that make a difference?

In vexflow5 it looks like a total mess on my browser, perhaps it is different you yours? (attached a screenshot)
<img width="275" alt="Screen Shot 2023-11-04 at 11 59 12" src="https://github.com/0xfe/vexflow/assets/13316019/32a401a7-6fcf-4ca2-b20f-c0bcbd29cea4">

**Comment by rvilarl** [comment]
@nitzanrh please try this one. I forgot to wait for the fonts. 

https://jsfiddle.net/92hj7a0c/

**Comment by AaronDavidNewman** [comment]
The dot placement seems better on vexflow 5.  

I also notice the flag is a little bigger - maybe too big?  The bottom flag overlaps the note head:

![image](https://github.com/0xfe/vexflow/assets/5438280/3e04888d-0d3d-489f-ab7e-b22af81fa258)

**Comment by rvilarl** [comment]
@AaronDavidNewman the notehead and the flag are using the same fontSize to keep them consistent. The lenght of the stem might be changed but I think that it is consitent with the intent of the font author. Please look at

https://vexflow.github.io/vexflow-examples/tools/glyphs.html

and under Bravura you will see

![image](https://github.com/0xfe/vexflow/assets/22865285/6a9e95dc-20af-49e3-8616-cbd90df9b010)

**Comment by nitzanrh** [comment]
> @nitzanrh please try this one. I forgot to wait for the fonts.
> 
> https://jsfiddle.net/92hj7a0c/

Hi @rvilarl ,

Yes this does look better, although personally I would have the dot closer. It also depends on what the distance to the next note would be.

Also, I noticed that while MuseScore aligns the dot relative to the stem, other notation companies align the note relative to the note, ie have the dot under the stem (in case the stem points down) 
example: 
![](https://press.rebus.community/app/uploads/sites/81/2018/04/dotted-eighth-note.png)

To me, this makes the most sense in terms of alignment because this way the dot doesn't affect the width of the note

**Comment by nitzanrh** [comment]
Also something I noticed which might be helpful:
When I used Chrome's inspector to to inspect the eighth note Notehead, its width reached all the way to the end of the beam, IE the eighth note's beam affected the Notehead's width - therefore 'pushing' the dot all the way to the right. If the notehead's width was not affected by the beam, the dot would appear next to the notehead

**Comment by nitzanrh** [comment]
UPDATE: in dot.js, I commented the line which sets the XShift for dot. I then manually set dot.setXShift(-5) when there is a dotted eighth note without a beam.

Can be marked as closed as far as I'm concerned :)

**Comment by rvilarl** [comment]
@nitzanrh which version of vexflow are you using?

**Comment by nitzanrh** [comment]
4.2.3On 25 Nov 2023, at 18:03, Rodrigo Vilar ***@***.***> wrote:﻿
@nitzanrh which version of vexflow are you using?
