### ISSUE TITLE
`ClefNote` might need to be updated for the new formatter.

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#845]
Ouch, that looks like a separate bug. It's possible `ClefNote` needs to be updated for the new formatter.

Also, can you share your changes to `modLeftPx` and `modRightPx` please? At some point I'll lump it all into a proper fix.

_Originally posted by @0xfe in https://github.com/0xfe/vexflow/issues/829#issuecomment-774517682_

**Comment by rvilarl** [comment]
in #829 this was thought to be a possible error as commented above.
Changing  `modLeftPx` and `modRightPx` in `getMetrics` from note.js

`const modLeftPx = (this.modifierContext ? this.modifierContext.state.left_shift : 0) + 12;`
`const modRightPx = (this.modifierContext ? this.modifierContext.state.right_shift : 0) + 12;`

the ClefNote overlaps like shown below: 

![image](https://user-images.githubusercontent.com/22865285/107111023-d37e3900-684c-11eb-9440-3486199e61e2.png)

**Comment by 0xfe** [comment]
This should be fixed with the #839 fix. Please let me know.

**Comment by rvilarl** [comment]
> This should be fixed with the #839 fix. Please let me know.

It is much better! The initial measures are now well aligned but the clef is still a problem even without the modification above. Please use the link:

https://michaelecke.com/pianoplay3x/ (I have updated it to vexflow master 5eb9275 and I have enabled the debugger in Formatter, should this help)

and load the following MusicXML file:

[Prelude_and_Fugue_in_C_major_-_J._S._Bach.zip](https://github.com/0xfe/vexflow/files/6096358/Prelude_and_Fugue_in_C_major_-_J._S._Bach.zip)

I observe the following problems:
- **ClefNotes overlap** with notes in **measure 32 & 33**
- **Notes too compresed** leaving space to the rigth in **measure 41**
- **Notes going beyond the measure** in **measures 34, 36, 39, 47, 48, 49, 57, 58 & 59**

It is worth looking at measure 41 specially and the errors above Vexflow `1.2.93` for reference https://michaelecke.com/pianoplay/

**Comment by 0xfe** [comment]
Thanks -- would you mind attaching some screenshots please?

**Comment by rvilarl** [comment]
![image](https://user-images.githubusercontent.com/22865285/110359215-80f78e80-803d-11eb-99a7-e66f1e4ddeb2.png)

I observe  the following problems:
- **ClefNotes overlap** with notes in **measure 32 & 33**
- **Notes too compresed** leaving space to the rigth in **measure 41 and perhaps 44**
- **Notes going beyond the measure** in **measures 34, 36, 39, 47, 48**

As I mentioned above I have enabled the debug for the formatter, this might help:
![image](https://user-images.githubusercontent.com/22865285/110360349-e6984a80-803e-11eb-9568-22e11510a0d1.png)

Below for reference some of the measures above with `1.2.93`. Here there is no issue.

![image](https://user-images.githubusercontent.com/22865285/110359894-5a862300-803e-11eb-8ece-751abc293cb6.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman the issue you mentioned in #839:`preCalculateMinTotalWidth` returning a value that is too low could be the reason for the reson why some notes above go beyond the measure.
@0xfe  are you happy to also look into that here or you prefer that I open another issue?

**Comment by 0xfe** [comment]
Thanks for the screenshots, @rvilarl.

- Yes, for notes going beyond the measure, that's `preCalculateMinTotalWidth`. Yes, please open a separate issue -- that would be great!
- For the clef overlapping, I'm pretty sure it has to do with the interaction between softmax and `ignore_ticks`. `ClefNote` and other elements don't take up ticks in the voice, so they effectively have `0` ticks. With softmax scaling, their spacing is multiplied by `0`, and they get pushed over the previous note.

**Comment by rvilarl** [comment]
@0xfe and what about the third issue? Notes getting too compresses like in measure 41?

In this regard I decided to practice Satie this afternoon and look what I found here the GraceNotes are also ovelapping

![image](https://user-images.githubusercontent.com/22865285/110389781-49044180-8065-11eb-9397-f58d425fd4b9.png)

Bellow with `1.2.93`

![image](https://user-images.githubusercontent.com/22865285/110389873-705b0e80-8065-11eb-9ea9-d83474fcb91e.png)

**Comment by 0xfe** [comment]
Ooh, I may have missed the "too compressed" thing -- I have no idea why that's happening. Any chance you can reproduce with a short fiddle? (I'd like to eliminate OpenSheetMusic from the equation.)

Re: grace notes, same issue as Clef -- zero ticks for `GraceNoteGroup`.

**Comment by rvilarl** [comment]
I do not think that I can help with fiddle for two reasons. I do not know:
- how to set up in fiddle the latest commit of vexflow.
- how to replicate such an arrangement of notes with grace notes, chords, ties,... using vexflow natively.

For someone knowing how to do that it should be easy to replicate the measures 1 & 2. I could provide the MusicXML file to see the details with MuseScore.

**Comment by 0xfe** [comment]
No problem, I think I can reproduce it.

**Comment by rvilarl** [comment]
@0xfe did you manage to figure out the error? can I do anythig?
